name: GitHub Snake Game

# This workflow generates a contribution graph "snake" animation and pushes it to the
# dedicated "output" branch. The README embeds the raw file from that branch.

on:
  # Run daily at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual run
  workflow_dispatch:
  # (Optional) keep on push to main to refresh quickly after activity
  push:
    branches:
      - main

# Explicit permissions (newer repos may default to read)
permissions:
  contents: write

# Prevent overlapping runs (e.g., manual + schedule)
concurrency:
  group: snake-animation
  cancel-in-progress: true

jobs:
  generate:
    name: Generate snake animation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVG / GIF assets
        id: snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # You can add / tweak palettes & variants here
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
          commit_message: "chore: update snake animation"
